const plaginObj = {};

const arrayForCard = [
  {
    number: "01",
    id: 1,
    adress: "adress",
    timeOfWorke: "time",
    header: "HEADER",
    text: "TEXT",
    mainimg: "/IMG/Background.jpg",
    twoimg: "/IMG/GITHUB.png",
    threimg: "/IMG/Background.jpg",
  },
  {
    number: "02",
    id: 2,
    adress: " ",
    timeOfWorke: " ",
    header: "HEADER",
    text: "TEXT",
    mainimg: "/IMG/Background.jpg",
  },
  {
    number: "03",
    id: 3,
    adress: " ",
    timeOfWorke: " ",
    header: "HEADER",
    text: "TEXT",
    mainimg: "/IMG/Background.jpg",
  },
  {
    number: "04",
    id: 4,
    adress: " ",
    timeOfWorke: " ",
    header: "HEADER",
    text: "TEXT",
    mainimg: "/IMG/Background.jpg",
  },
];

let numberButton = "";
let arrayForCardFilter = [];
let mainModal = "";
