const arrayForCardMain = [
  {
    number: "01",
    id: 1,
    header: "КОРСО",
    address: "ADDRESS: ул. Кабельная, 34a, Самара, Самарская обл",
    timeOfWorke: "TIMEOFWORKE: 7:00 – 22:00 ПН-ВС",
    mainimg: "/IMG/CORSO/MAIN.jpeg",
    moreInfo: "/HTML/MOREINFO.HTML",
    googleAddress:
      "https://www.google.com/maps/search/прием+вторсытья+Самара/@53.0965959,49.4977208,10z?entry=ttu",
  },
  {
    number: "02",
    id: 2,
    header: "ЭкоВоз",
    address: "ADDRESS: Чернореченская ул., 6",
    timeOfWorke: "TIMEOFWORKE: 08:00–18:00 ПН-СБ",
    mainimg: "/IMG/ECOVOZ/MAIN.jpg",
    moreInfo: "/HTML/MOREINFO.HTML",
    googleAddress:
      "https://www.google.com/maps/place/%D0%AD%D0%BA%D0%BE%D0%B2%D0%BE%D0%B7/@53.193851,49.954653,11z/data=!4m10!1m2!2m1!1z0KbQtdC90YLRgCDQv9C-INC_0LXRgNC10YDQsNCx0L7RgtC60LUg0L7RgtGF0L7QtNC-0LI!3m6!1s0x41661e656ef158e5:0x96df718f72b09fd7!8m2!3d53.193851!4d50.128775!15sCjXQptC10L3RgtGAINC_0L4g0L_QtdGA0LXRgNCw0LHQvtGC0LrQtSDQvtGC0YXQvtC00L7QspIBEHJlY3ljbGluZ19jZW50ZXLgAQA!16s%2Fg%2F11hzwbws21?entry=ttu",
  },
  {
    number: "03",
    id: 3,
    header: "ВТОРГРУП",
    address: "ADDRESS: Самара улица Авиационная 30 ",
    timeOfWorke: "TIMEOFWORKE: круглосуточно ПН-ВС",
    mainimg: "/IMG/VTORGROUP/MAIN.jpg",
    moreInfo: "/HTML/MOREINFO.HTML",
    googleAddress:
      "https://www.google.com/maps/place/Втор-Групп/@53.0965959,49.4977208,10z/data=!4m10!1m2!2m1!1z0L_RgNC40LXQvCDQstGC0L7RgNGB0YvRgtGM0Y8g0KHQsNC80LDRgNCw!3m6!1s0x41661dd7263c682b:0xff919f92f7d495ba!8m2!3d53.1825087!4d50.1520821!15sCirQv9GA0LjQtdC8INCy0YLQvtGA0YHRi9GC0YzRjyDQodCw0LzQsNGA0LCSARJzY3JhcF9tZXRhbF9kZWFsZXLgAQA!16s%2Fg%2F11h2n4gx9w?entry=ttu",
  },
  {
    number: "04",
    id: 4,
    header: "ВТОРМАРКЕТ",
    address: "ADDRESS: Заводское ш., 5Б корп 7, Самара, Самарская обл., ",
    timeOfWorke: "TIMEOFWORKE: Круглосуточно ПН-ВС",
    mainimg: "/IMG/VTORMARKET/MAIN.jpg",
    moreInfo: "/HTML/MOREINFO.HTML",
    googleAddress:
      "https://www.google.com/maps/place/Втормаркет/@53.2044705,50.0879567,12z/data=!4m10!1m2!2m1!1z0JLQotCe0KDQoNCc0JDQoNCa0JXQoiDQodCc0JDQkA!3m6!1s0x41661b8c1b54705f:0xd127dd770a20601e!8m2!3d53.1797838!4d50.2088033!15sCiHQktCi0J7QoNCc0JDQoNCa0JXQoiDQodCQ0JzQkNCg0JBaIyIh0LLRgtC-0YDQvNCw0YDQutC10YIg0YHQsNC80LDRgNCwkgEYd2FzdGVfbWFuYWdlbWVudF9zZXJ2aWNl4AEA!16s%2Fg%2F1tdpkmqk?entry=ttu",
  },
];
